name: 'UMM-S Updater'
description: 'Publish UMM-S updates to CMR'
inputs:
  umm-s-json:
    description: 'JSON file containing new UMM-S contents'
    required: true
  provider:
    description: 'CMR Provider ID'
    required: true
  env:
    description: 'Venue to make update'
    required: true
  association-file:
    description: 'File containing newline separated list of concept IDs to associate with this UMM-S entry'
    required: false
  version:
    description: 'Service version to be substituted in to UMM-S entry'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.umm-s-json}}
    - ${{inputs.provider}}
    - ${{inputs.env}}
    - ${{inputs.association-file }}
