on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test CMR UMM-S updater Github Action
    steps:
      - name: UMM-S Updater Step
        id: umm-s-update
        uses: skorper/cmr-publish-umms-action@0.0.21
        with:
          umm-s-json: 'cmr/test.json'
          provider: 'POCLOUD'
          env: 'uat'
          version: '1.2.3'
        env:
          cmr_user: ${{secrets.CMR_USER}}
          cmr_pass: ${{secrets.CMR_PASS}}